export abstract class DRReddit {
    abstract roleExists(name: string): Promise<boolean>

    abstract getRole(name: string): Promise<DRRole>

    abstract createRole(role: DRRole): Promise<DRRole>
    abstract createRole(name: string, sprites: DRSpriteList, flairs: DRFlairList): Promise<DRRole>
}

export interface DRRole {
    name: string,
    sprites: DRSpriteList,
    flairs: DRFlairList
}

export const ROLES = {
    AKANE_OWARI: "AKANE_OWARI",
    ALTER_EGO: "ALTER_EGO",
    ANGIE_YONAGA: "ANGIE_YONAGA",
    AOI_ASAHINA: "AOI_ASAHINA",
    BYAKUYA_TOGAMI: "BYAKUYA_TOGAMI",
    CELESTE: "CELESTE",
    CHIAKI_NANAMI: "CHIAKI_NANAMI",
    CHIHIRO_FUJISAKI: "CHIHIRO_FUJISAKI",
    CHISA_YUKIZOME: "CHISA_YUKIZOME",
    DAISAKU_BANDAI: "DAISAKU_BANDAI",
    FUYUHIKO_KUZURYUU: "FUYUHIKO_KUZURYUU",
    GENOCIDER: "GENOCIDER",
    GONTA_GOKUHARA: "GONTA_GOKUHARA",
    GREAT_GOZU: "GREAT_GOZU",
    GUNDHAM_TANAKA: "GUNDHAM_TANAKA",
    HAIJI_TOWA: "HAIJI_TOWA",
    HAJIME_HINATA: "HAJIME_HINATA",
    HIFUMI_YAMADA: "HIFUMI_YAMADA",
    HIMIKO_YUMENO: "HIMIKO_YUMENO",
    HIROKO_HAGAKURE: "HIROKO_HAGAKURE",
    HIYOKO_SAIONJI: "HIYOKO_SAIONJI",
    IBUKI_MIODA: "IBUKI_MIODA",
    IMPOSTER: "IMPOSTER",
    IZURU_KAMUKURA: "IZURU_KAMUKURA",
    JATARO_KEMURI: "JATARO_KEMURI",
    JUNKO_ENOSHIMA: "JUNKO_ENOSHIMA",
    JUNKO_IKUSABA: "JUNKO_IKUSABA",
    JUZO_SAKAKURA: "JUZO_SAKAKURA",
    KAEDE_AKAMATSU: "KAEDE_AKAMATSU",
    KAITO_MOMOTA: "KAITO_MOMOTA",
    KAMISHIRO_YUUTO: "KAMISHIRO_YUUTO",
    KAZUICHI_SODA: "KAZUICHI_SODA",
    KAZUO_TENGAN: "KAZUO_TENGAN",
    KEEBO: "KEEBO",
    KENISHIRO: "KENISHIRO",
    KIRUMI_TOJO: "KIRUMI_TOJO",
    KIYONDO_ISHIDA: "KIYONDO_ISHIDA",
    KIYOTAKA_ISHIMARU: "KIYOTAKA_ISHIMARU",
    KOICHI_KIZAKURA: "KOICHI_KIZAKURA",
    KOKICHI_OMA: "KOKICHI_OMA",
    KOMARU_NAEGI: "KOMARU_NAEGI",
    KOREKIYO_SHINGUJI: "KOREKIYO_SHINGUJI",
    KOTOKO_UTSUGI: "KOTOKO_UTSUGI",
    KUROKUMA: "KUROKUMA",
    KYOKO_KIRIGIRI: "KYOKO_KIRIGIRI",
    KYOSUKE_MUNAKATA: "KYOSUKE_MUNAKATA",
    LEON_KUWATA: "LEON_KUWATA",
    MADARAI: "MADARAI",
    MAHIRU_KOIZUMI: "MAHIRU_KOIZUMI",
    MAKI_HARUKAWA: "MAKI_HARUKAWA",
    MAKOTO_NAEGI: "MAKOTO_NAEGI",
    MASARU_DAIMON: "MASARU_DAIMON",
    MECHAMARU_NIDAI: "MECHAMARU_NIDAI",
    MIAYA_GEKKOGAHARA: "MIAYA_GEKKOGAHARA",
    MIKAN_TSUMIKI: "MIKAN_TSUMIKI",
    MIU_IRUMA: "MIU_IRUMA",
    MONACA_TOWA: "MONACA_TOWA",
    MONDO_OWADA: "MONDO_OWADA",
    MONODAM: "MONODAM",
    MONOKID: "MONOKID",
    MONOKUMA: "MONOKUMA",
    MONOMI: "MONOMI",
    MONOPHANIE: "MONOPHANIE",
    MONOSUKE: "MONOSUKE",
    MONOTARO: "MONOTARO",
    MUKURO_IKUSABA: "MUKURO_IKUSABA",
    NAGISA_SHINGETSU: "NAGISA_SHINGETSU",
    NAGITO_KOMAEDA: "NAGITO_KOMAEDA",
    NATSUMI_KUZURYUU: "NATSUMI_KUZURYUU",
    NEKOMARU_NIDAI: "NEKOMARU_NIDAI",
    PEKO_PEKOYAMA: "PEKO_PEKOYAMA",
    RANTARO_AMAMI: "RANTARO_AMAMI",
    RURUKA_ANDO: "RURUKA_ANDO",
    RYOKO_OTANASHI: "RYOKO_OTANASHI",
    RYOMA_HOSHI: "RYOMA_HOSHI",
    SAIYAN_HAJIME: "SAIYAN_HAJIME",
    SAKURA_OGAMI: "SAKURA_OGAMI",
    SANTA_SHIKIBA: "SANTA_SHIKIBA",
    SAYAKA_MAIZONO: "SAYAKA_MAIZONO",
    SEIKO_KIMURA: "SEIKO_KIMURA",
    SHIROKUMA: "SHIROKUMA",
    SHUICHI_SAIHARA: "SHUICHI_SAIHARA",
    SONIA_NEVERMIND: "SONIA_NEVERMIND",
    SONOSUKE_IZAYOI: "SONOSUKE_IZAYOI",
    TAICHI_FUJISAKI: "TAICHI_FUJISAKI",
    TENKO_CHABASHIRA: "TENKO_CHABASHIRA",
    TERUTERU_HANAMURA: "TERUTERU_HANAMURA",
    TOKO_FUKAWA: "TOKO_FUKAWA",
    TSUMUGI_SHIROGANE: "TSUMUGI_SHIROGANE",
    USAMI: "USAMI",
    YASUHIRO_HAGAKURE: "YASUHIRO_HAGAKURE",
    YASUKE_MATSUDA: "YASUKE_MATSUDA",
    YUI_SAMIDARE: "YUI_SAMIDARE",
    YUTA_ASAHINA: "YUTA_ASAHINA",
} as const

export const SUBREDDITS = {
    DANGANRONPA: "danganronpa",
    DANGANROLEPLAY: "danganroleplay",
} as const

export interface DRSpriteCategory {
    name: string,
    icon: string,
    sprites: DRSpriteList
}

export type DRFlairList = null | { [key: string]: string }
export type DRSpriteList = null | string[] | { [key: string]: DRSpriteCategory }